import Head from 'next/head';
import Image from 'next/image';
import Footer from '../components/Footer';
import Header from '../components/Header';
import NavBar from '../components/NavBar';
import Results from '../components/Results';
import genreList from '../util/requests';

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>MovieDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <NavBar />
      <Results data={data} />
      <Footer />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const baseURL = 'https://api.themoviedb.org/3';

  const res = await fetch(
    `${baseURL}${genreList[genre]?.url || genreList.fetchTrending.url}`
  );
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}
